### ISSUE TITLE
Incorporate Draft Feedback

### ISSUE THREAD

**Issue by EhrenbruderRoschtbraten** [Ctrl-Alt-Defeat-Foundation-Models/informatiCup2024Paper#15]
Incorporate the feedback of the draft. The following things have to be done:

- [x] Good structure, but you shouldn’t have so many subsections for “Generative Models” and “Detector Models”. Try breaking everything into paragraphs. Also, the “Generating Models” section should be “Generative Models”.
- [x] Please include details regarding InformatiCup 2024 in your intro and slides.
- [x] Please include citations and references in both your report and your slides

**Comment by RaphaW** [comment]
Not sure what they want with paragraphs

**Comment by EhrenbruderRoschtbraten** [comment]
> Not sure what they want with paragraphs

I guess they want, that we dont break the sections Generative models and detector models in two subsections for texts and images, but rather make paragraphs for each model without forming subsections aroud the text and image ones
